### ISSUE TITLE
[CONFLICT] Item Piles and OBS Utils use the same CSS name for custom settings menus

### ISSUE THREAD

**Issue by 9ryex5** [FaeyUmbrea/obs-utils#115] opened 2023-03-30 02:51 UTC
I run Find the Culprit and found that OBS Utils is causing visual problems in [Item Piles](https://foundryvtt.com/packages/item-piles) settings.
To reproduce, enable both modules on a clean world and open [Item Piles](https://foundryvtt.com/packages/item-piles) settings.
![image](https://user-images.githubusercontent.com/43207603/228715466-4363e8e7-35a0-40ee-a1d2-12ffdea17772.png)

**Comment by FaeyUmbrea** [comment] 2023-03-30 03:03
Not a bug. 
This conflict should be reported to Item Piles as well.
Conflict is due to the settings css-class used by both module's custom config menus.

**Comment by FaeyUmbrea** [comment] 2023-04-16 18:25
Closed in 2.1.0

**Closed by FaeyUmbrea** 2023-04-16 18:25 UTC
