### ISSUE TITLE
Character art showing when permissions are changed

### ISSUE THREAD

**Issue by Kubixcube** [FaeyUmbrea/obs-utils#124] opened 2023-09-10 13:28 UTC
**Context** : I use Foundry V11 and Pathfinder 1. Using both "Stream" and "StreamGame" as sources. This problem happened even when this module is the only active (and its dependencies).

**Problem** : Each time I change the permission of a character, it shows its art window on the "Stream" source multiple times (and never goes off).

**Reproduction** : Having both sources active on OBS, and changing the permission of a character (NPC). Image shows in "Steam" source. Sometimes, it needs to be in combat and do "next turn" (to refresh I guess) and the image shows on that moment.

![image](https://github.com/FaeyUmbrea/obs-utils/assets/62657097/488551c9-bfec-42ce-8657-5a6b8f20fa9e)

**Comment by FaeyUmbrea** [comment] 2023-09-10 13:32
Oh that is super weird.

I don't see behaviour like this with any of the systems I commonly use, I think this may be caused by either the PF1 System or any of the modules you are using alongside it.

You should be able to close it by using interact on the /stream source.

Since this is either System or Module specific, it'd be great if you could use "Who's the culprit" to isolate the issue.

**Comment by Kubixcube** [comment] 2023-09-10 13:58
As said in my first message, I also tried with no modules other than OBS-Utils and its dependencies, and the issue is still there.
I don't know how I can verify if it's system dependent and how to fix it.

**Comment by FaeyUmbrea** [comment] 2023-09-10 14:06
Unfortunately I'm entirely unable to reproduce this issue locally. 
I'm running V11 and the latest version of the Pathfinder 1 System with only my module enabled and I don't see the behaviour described

**Comment by Kubixcube** [comment] 2023-09-10 14:38
Have you tried changing permission while in combat (and doing "next turn") ? I have reinstalled the module and still have the issue while in combat.

**Comment by FaeyUmbrea** [comment] 2023-09-10 14:46
Thanks for giving me the Hint with the Combat. I was able to reproduce the issue now. But I was also able to reproduce it with all modules disabled. It appears that the PF1 System has a bug that tries to render the characters's Stat-Sheet in a few edge cases.

Since it appears to be a system but, I am going to close this issue. Please report the Problem to the PF1 System development Team.

In the Meantime, you can use the "Interact" mode in OBS to manually close the sheet opened by the bug.

**Closed by FaeyUmbrea** 2023-09-10 14:46 UTC

**Comment by Kubixcube** [comment] 2023-09-10 14:48
Thank you, I will do that !

**Comment by Kubixcube** [comment] 2023-09-10 15:24
I tried to reproduce the same bug with a DnD5 table and it appears too. PF1 dev said that it is not related to the system. I suppose it is either a core Foundry bug or a module bug...

**Comment by FaeyUmbrea** [comment] 2023-09-10 15:25
It definitely also occurs for me with all modules disabled, so it might be core foundry

**Comment by Kubixcube** [comment] 2023-09-10 15:40
Do you think you can fix that by closing those tabs automatically ? Just like "/game" do ? Also, I don't know how to report that bug to foundy...

**Comment by FaeyUmbrea** [comment] 2023-09-10 15:49
I can't properly detect these opening because it's a bugged UI element that, at least in my testing, did not seem to trigger the correct events I'd need to close it automatically.
